[SECURITY-991] NPE When registering null AuthConfigProvider on JBossAuthConfigFactory
picketbox/picketbox pull request #80
Opened 2018-06-13 10:20 UTC by ivassile

https://issues.jboss.org/browse/SECURITY-991

Addition to PR https://github.com/picketbox/picketbox/pull/78
Changes needed to consider that keyToAuthConfigProviderMap can contains
null values for AuthConfigProvider.

2018-06-19 13:59 UTC, sguilhen requested changes

2018-06-19 13:59 UTC, sguilhen commented on security-jboss-sx/jbosssx/src/main/java/org/jboss/security/auth/message/config/JBossAuthConfigFactory.java
> -      }
I think the above code must be retained. When the provider is null the method must return all keys.

2018-06-19 15:40 UTC, ivassile commented
@sguilhen Thanks for the review. I've submitted the requested changes.

2018-06-21 12:17 UTC, sguilhen approved these changes

2018-06-21 12:18 UTC, merged